### ISSUE TITLE
Stat boxes not showing

### ISSUE THREAD

**Issue by ronknight** [ronknight/InventorySystem#1]
Stat boxes only shows up when using the default user. Need to enable stat boxes for Admin Group.

**Comment by GregsGrog** [comment]
Do you have any more information about this bug?

**Comment by demartini** [comment]
Hi,

I believe this is not a bug, it is a condition.

At `line 20` of the [`InventorySystem/application/views/dashboard.php`](https://github.com/ronknight/InventorySystem/blob/b53d2ece1e876394c2c6952a73fa1e5607230175/application/views/dashboard.php#L20) file.

https://github.com/ronknight/InventorySystem/blob/b53d2ece1e876394c2c6952a73fa1e5607230175/application/views/dashboard.php#L20

We have a variable saying that if the user **is admin** to display the content, if not they will not display anything.

**Comment by ronknight** [comment]
Yes it is indeed based on a value that is stored on the database. I tried changing the database value of a regular user to the same value that a administrator would have but the stat boxes still don't show up even if the regular user is already converted to an admin.

**Comment by nitorplus** [comment]
At line 32 of the InventorySystem/application/controllers/Dashboard.php file.

`$is_admin = ($user_id == 1) ? true :false;`

Only user with user_id 1 is ever set to admin.

**Comment by ronknight** [comment]
good catch @nitorplus. Thanks
