### ISSUE TITLE
Only shows index

### ISSUE THREAD

**Issue by Mr-Tech-13** [ronknight/InventorySystem#18]
An uncaught Exception was encountered
Type: mysqli_sql_exception

Message: Unknown database 'stock'

Filename: C:\xampp\htdocs\InventorySystem\system\database\drivers\mysqli\mysqli_driver.php

Line Number: 201

Backtrace:

File: C:\xampp\htdocs\InventorySystem\application\core\MY_Controller.php
Line: 7
Function: __construct

File: C:\xampp\htdocs\InventorySystem\application\core\MY_Controller.php
Line: 17
Function: __construct

File: C:\xampp\htdocs\InventorySystem\application\controllers\Auth.php
Line: 10
Function: __construct

File: C:\xampp\htdocs\InventorySystem\index.php
Line: 315
Function: require_once

this is the error that i get

**Comment by ronknight** [comment]
Please follow steps 3 to 6 on the installation instruction. Let me know if that works.

**Comment by Mr-Tech-13** [comment]
Thats where i am confused, how do i make a database

**Comment by Mr-Tech-13** [comment]
figured it out, now i have another issu
![Screenshot (28)](https://user-images.githubusercontent.com/81822275/170841437-62b879a9-0d5a-43a9-bae9-569628f0ade0.png)
e

**Comment by Mr-Tech-13** [comment]
got to http://localhost/InventorySystem/auth/login but then showed this

Not Found
The requested URL was not found on this server.

Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 Server at localhost Port 80

**Comment by Mr-Tech-13** [comment]
Got it to login now, but every time i get this popup
DataTables warning: table id=manageTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by LOENS2** [comment]
I think that might be a problem related to case sensitivity

**Comment by nathanzky** [comment]
How can I add attributes as date?
