### ISSUE TITLE
could you please full documentation of projects it's kind of hard to understand with all different files and their functions

### ISSUE THREAD

**Issue by Abhishekrkd** [ronknight/InventorySystem#7]

**Comment by ronknight** [comment]
That is the problem. This project doesn't have any documentation. If you would like to start documenting, I would gladly help.

**Comment by Abhishekrkd** [comment]
Okay no problem
Do you have any ER diagram to represent different pages and database tables
connection with each other ? Or any written material which can help me to
do so

**Comment by ronknight** [comment]
I don't have any of those. I got this project off the web, I did the readme by myself by testing it locally.

Original Sourcecode from CodeFolder - https://codersfolder.com/2018/02/stock-management-system-v2-codeigniter/
